title: "Red de Literatura Electrónica Latinoamericana"
description: "Lit(e)Lat - Red de Literatura Electrónica Latinoamericana"
url: "https://litelat.net"
baseurl: ""

permalink: /:title/

markdown: kramdown
highlighter: rouge

future: true

defaults:
  - scope:
      path: "_posts/es"
    values:
      layout: post
      lang: es
  - scope:
      path: "_posts/pt"
    values:
      layout: post
      lang: pt
  - scope:
      path: "_pages/es"
    values:
      layout: page
      lang: es
  - scope:
      path: "_pages/pt"
    values:
      layout: page
      lang: pt

include:
  - _pages

plugins:
  - jekyll-seo-tag

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
